using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FarmCentral.Models.ModelsDB
{
    public class Employee
    {
        //Annotations
        //https://learn.microsoft.com/en-us/ef/ef6/modeling/code-first/data-annotations
        //Accessed 25 May 2023
        //Autogenerated 5 character string for ID
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Display(Name = "ID")]
        public Guid EmployeeId { get; set; }

        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string EmployeeEmail { get; set; } = null!;

        [Required]
        [Display(Name = "Name")]
        public string EmployeeName { get; set; } = null!;

        [Required] 
        public string EmployeePassword { get; set; } = null!;
    }
}
