using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace FarmCentral.Models.ModelsDB
{
    public class Farmer
    {
        //Annotations
        //https://learn.microsoft.com/en-us/ef/ef6/modeling/code-first/data-annotations
        //Accessed 25 May 2023
        //Autogenerated 5 character string for ID
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Display(Name = "ID")]
        public Guid FarmerId { get; set; }

        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string FarmerEmail { get; set; } = null!;

        [Required]
        [Display(Name = "Name")]
        public string FarmerName { get; set; } = null!;

        [Required]
        public string FarmerPassword { get; set; } = null!;

        //List of farmer products
        public ICollection<Product> FarmerProducts { get; set; } = new List<Product>();
    }
}
